AllCops:
  TargetRubyVersion: 3.3

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LeadingCommentSpace:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Exclude:
    - 'test/**/*'
