module Prism
  class ClassNode
    def constant_path: () -> Prism::ConstantReadNode
                     | ...
  end

  class ModuleNode
    def constant_path: () -> Prism::ConstantReadNode
                     | ...
  end

  class Comment
    def slice: () -> String
  end

  class ConstantWriteNode
    def value: () -> CallNode
             | ...
  end
end
